-- Anand Technologies — Supabase Product Seed
-- Run AFTER schema.sql
-- All 60+ products from the real Google Drive catalog
-- datasheet_url: update with actual Supabase storage URLs after uploading PDFs

INSERT INTO products (name, slug, category, short_spec, frequency_range, description, specs) VALUES

-- ── GSM / LTE ANTENNAS ──────────────────────────────────────────────────────
('AT-ANT-QGSM-SMA210-3.5(SL)', 'at-ant-qgsm-sma210-35-sl', 'gsm-lte-antennas', 'Quad-band GSM Sleeve Antenna, SMA, 210mm', '824–2170 MHz', 'Quad-band GSM/GPRS/EDGE sleeve-type external antenna with SMA male connector and 210mm cable.', '{"Frequency":"824–960 / 1710–2170 MHz","Gain":"3.5 dBi","Type":"Sleeve","Connector":"SMA Male","Cable":"RG174, 210mm","Impedance":"50 Ω","VSWR":"< 2.0:1"}'),
('AT-ANT-QGSM-SMA110-3.0(SL)', 'at-ant-qgsm-sma110-30-sl', 'gsm-lte-antennas', 'Quad-band GSM Sleeve Antenna, SMA, 110mm', '824–2170 MHz', 'Compact quad-band GSM sleeve antenna with SMA male connector and 110mm cable.', '{"Frequency":"824–2170 MHz","Gain":"3.0 dBi","Connector":"SMA Male","Cable":"RG174, 110mm","Impedance":"50 Ω","VSWR":"< 2.0:1"}'),
('AT-ANT-QGSM-SMA305-5.0(SL)', 'at-ant-qgsm-sma305-50-sl', 'gsm-lte-antennas', 'Quad-band GSM Sleeve Antenna, SMA, 305mm', '824–2170 MHz', 'Long-cable quad-band GSM sleeve antenna for panel-mounted and DIN-rail industrial applications.', '{"Frequency":"824–2170 MHz","Gain":"5.0 dBi","Connector":"SMA Male","Cable":"RG174, 305mm","Impedance":"50 Ω","VSWR":"< 2.0:1"}'),
('AT-ANT-QGSM-SMAR70-3.0', 'at-ant-qgsm-smar70-30', 'gsm-lte-antennas', 'Quad-band GSM Modem Antenna, SMA RA, 70mm', '824–2170 MHz', 'Right-angle SMA modem antenna for GSM/3G modems. 70mm stub.', '{"Frequency":"824–2170 MHz","Gain":"3.0 dBi","Connector":"SMA Male RA","Length":"70mm","Impedance":"50 Ω","VSWR":"< 2.5:1"}'),
('AT-ANT-QGSM-SMAR90-3.0', 'at-ant-qgsm-smar90-30', 'gsm-lte-antennas', 'Quad-band GSM Modem Antenna, SMA RA, 90mm', '824–2170 MHz', 'Compact right-angle stub antenna for GSM/3G/4G modem boards. SMA male right-angle.', '{"Frequency":"824–2170 MHz","Gain":"3.0 dBi","Connector":"SMA Male RA","Length":"90mm","Impedance":"50 Ω","VSWR":"< 2.5:1"}'),
('AT-ANT-QGSM-UFL1.13-0.18-3.0', 'at-ant-qgsm-ufl-018-30', 'gsm-lte-antennas', 'Quad-band GSM Internal Antenna, UFL, 180mm', '824–2170 MHz', 'Internal PCB-mount quad-band GSM antenna with UFL connector and 1.13mm coax, 180mm cable.', '{"Frequency":"824–2170 MHz","Gain":"3.0 dBi","Connector":"UFL (IPEX)","Cable":"1.13mm, 180mm","Impedance":"50 Ω","Mount":"Adhesive / PCB"}'),
('AT-ANT-QGSM-FGNW-NF600-5.0', 'at-ant-qgsm-fgnw-nf600-50', 'gsm-lte-antennas', 'Quad-band GSM Fiberglass Networking Antenna, N Female, 5 dBi', '824–2170 MHz', 'Heavy-duty outdoor fiberglass GSM antenna. Suitable for cellular base repeaters and industrial routers.', '{"Frequency":"824–2170 MHz","Gain":"5.0 dBi","Connector":"N Female","Radome Length":"600mm","Material":"Fibreglass","IP Rating":"IP65","VSWR":"< 1.5:1"}'),
('AT-ANT-QGSM-HMM-SMA174-3-5.0', 'at-ant-qgsm-hmm-sma174-3-50', 'gsm-lte-antennas', 'Quad-band GSM Helical Antenna, SMA, 5.0 dBi', '824–2170 MHz', 'Helical coil quad-band GSM antenna with SMA male connector.', '{"Frequency":"824–2170 MHz","Gain":"5.0 dBi","Type":"Helical","Connector":"SMA Male","Cable":"RG174, 3m","Impedance":"50 Ω","VSWR":"< 2.0:1"}'),
('AT-ANT-CDMA-SMA210-3.5(SL)', 'at-ant-cdma-sma210-35-sl', 'gsm-lte-antennas', 'CDMA Sleeve Antenna, SMA, 210mm', '824–1990 MHz', 'CDMA 800/1900 MHz sleeve antenna with SMA male connector and 210mm cable.', '{"Frequency":"824–894 / 1850–1990 MHz","Gain":"3.5 dBi","Type":"Sleeve","Connector":"SMA Male","Cable":"RG174, 210mm","Impedance":"50 Ω","VSWR":"< 2.0:1"}'),
('AT-ANT-LTE-B3-SMA260-3.5(SL)', 'at-ant-lte-b3-sma260-35-sl', 'gsm-lte-antennas', 'LTE Band 3 Sleeve Antenna, SMA, 260mm', '1710–1880 MHz', 'LTE Band 3 (1800 MHz) sleeve antenna — the primary band for Indian 4G deployments.', '{"Frequency":"1710–1880 MHz","Gain":"3.5 dBi","Type":"Sleeve","Connector":"SMA Male","Cable":"RG174, 260mm","Impedance":"50 Ω","VSWR":"< 2.0:1"}'),
('AT-ANT-LTE-B28-SMA260-3.5(SL)', 'at-ant-lte-b28-sma260-35-sl', 'gsm-lte-antennas', 'LTE Band 28 Sleeve Antenna, SMA, 260mm', '700–803 MHz', 'LTE Band 28 (700 MHz APT) sleeve antenna for rural and deep-indoor 4G coverage.', '{"Frequency":"700–803 MHz","Gain":"3.5 dBi","Type":"Sleeve","Connector":"SMA Male","Cable":"RG174, 260mm","Impedance":"50 Ω","VSWR":"< 2.0:1"}'),
('AT-ANT-LTE-B71-SMA290-3.5(SL)', 'at-ant-lte-b71-sma290-35-sl', 'gsm-lte-antennas', 'LTE Band 71 Sleeve Antenna, SMA, 290mm', '617–698 MHz', 'LTE Band 71 (600 MHz) sleeve antenna for extended rural coverage.', '{"Frequency":"617–698 MHz","Gain":"3.5 dBi","Type":"Sleeve","Connector":"SMA Male","Cable":"RG174, 290mm","Impedance":"50 Ω","VSWR":"< 2.0:1"}'),
('AT-ANT-4G-LTE-SMA3-200', 'at-ant-4g-lte-sma3-200', 'gsm-lte-antennas', '4G LTE Omni Antenna, SMA, 3 dBi, 200mm', '700–2700 MHz', 'Wideband 4G LTE omnidirectional antenna covering all major LTE bands from 700 MHz to 2700 MHz.', '{"Frequency":"700–2700 MHz","Gain":"3 dBi","Connector":"SMA Male","Cable":"200mm","Impedance":"50 Ω","VSWR":"< 2.5:1"}'),
('AT-ANT-4G-LTE-SMA5-250', 'at-ant-4g-lte-sma5-250', 'gsm-lte-antennas', '4G LTE Omni Antenna, SMA, 5 dBi, 250mm', '700–2700 MHz', 'High-gain wideband 4G LTE antenna for CPE routers and industrial gateways.', '{"Frequency":"700–2700 MHz","Gain":"5 dBi","Connector":"SMA Male","Cable":"250mm","Impedance":"50 Ω","VSWR":"< 2.5:1"}'),
('AT-ANT-QGSM-FGNW-NF213-500-5.5', 'at-ant-qgsm-fgnw-nf213-500-55', 'gsm-lte-antennas', 'GSM Fiberglass Networking Antenna, N Female, 5.5 dBi', '824–2170 MHz', 'Outdoor fiberglass omni GSM/3G antenna. N Female connector, 500mm radome.', '{"Frequency":"824–2170 MHz","Gain":"5.5 dBi","Connector":"N Female","Radome":"500mm","IP Rating":"IP65","VSWR":"< 1.5:1"}'),

-- ── GPS / GNSS ANTENNAS ─────────────────────────────────────────────────────
('AT-ANT-GPSE-SMA-MM174-5.0TCS', 'at-ant-gpse-sma-mm174-50tcs', 'gps-gnss-antennas', 'GPS External Active Antenna, SMA, 28dB LNA, 5m Cable', '1575.42 MHz', 'GPS L1 active external antenna with integrated 28 dB LNA. SMA male with 5m RG174 cable.', '{"Frequency":"1575.42 MHz","LNA Gain":"28 dB","Noise Figure":"< 1.5 dB","Connector":"SMA Male","Cable":"RG174, 5m","Supply Voltage":"2.7–5.5V DC","Current":"< 15 mA","IP Rating":"IP65"}'),
('AT-ANT-GPSE-SMA-MM174-2.8NM', 'at-ant-gpse-sma-mm174-28nm', 'gps-gnss-antennas', 'GPS External Active Antenna, SMA, 28dB LNA, 2.8m Cable', '1575.42 MHz', 'GPS L1 active antenna with 28 dB LNA and 2.8m RG174 cable.', '{"Frequency":"1575.42 MHz","LNA Gain":"28 dB","Connector":"SMA Male","Cable":"RG174, 2.8m","Supply Voltage":"2.7–5.5V","Current":"< 15 mA","IP Rating":"IP65"}'),
('AT-ANT-GPSE-SMAM-MM174-30-10', 'at-ant-gpse-smam-mm174-30-10', 'gps-gnss-antennas', 'GPS External Active Antenna, SMA, 30dB LNA, 10m Cable', '1575.42 MHz', 'Long-cable GPS active antenna with 30 dB LNA for extended cable runs.', '{"Frequency":"1575.42 MHz","LNA Gain":"30 dB","Connector":"SMA Male","Cable":"RG174, 10m","Supply Voltage":"3.3–5V","Current":"< 20 mA","IP Rating":"IP65"}'),
('AT-ANT-GPSGNSS-UFL1.13-INTERNAL-28', 'at-ant-gpsgnss-ufl-internal-28', 'gps-gnss-antennas', 'GPS/GNSS Internal Active Antenna, UFL, 28dB LNA', '1575.42 MHz', 'Miniature internal GPS/GNSS active patch antenna with UFL connector and 28 dB LNA.', '{"Frequency":"1575.42 MHz","LNA Gain":"28 dB","Connector":"UFL (IPEX)","Dimensions":"25×25×4mm","Supply Voltage":"1.8–5.5V","Current":"< 10 mA","Mount":"PCB / adhesive"}'),
('AT-ANT-GPSGNSS-UFL1.13-120-INT-18', 'at-ant-gpsgnss-ufl-120-int-18', 'gps-gnss-antennas', 'GPS/GNSS Internal Antenna, UFL, 18dB LNA, 120mm Cable', '1575.42 MHz', 'Internal GPS/GNSS patch antenna with UFL connector and 120mm cable. 18 dB LNA.', '{"Frequency":"1575.42 MHz","LNA Gain":"18 dB","Connector":"UFL","Cable":"1.13mm, 120mm","Supply Voltage":"1.8–3.6V","Current":"< 8 mA"}'),
('AT-ANT-CSCM-SMA174-28-3.0', 'at-ant-cscm-sma174-28-30', 'gps-gnss-antennas', 'GPS/GLONASS/IRNSS Combo Antenna, SMA, 28dB, 3m', '1575/1602/1176–1227 MHz', 'Multi-constellation combo antenna supporting GPS L1, GLONASS L1, and IRNSS.', '{"Frequency":"GPS L1 / GLONASS L1 / IRNSS L1+L5","LNA Gain":"28 dB","Connector":"SMA Male","Cable":"RG174, 3m","Supply Voltage":"2.7–5.5V","IP Rating":"IP65","Impedance":"50 Ω"}'),
('AT-ANT-CSCM-SMA316-28-3.0', 'at-ant-cscm-sma316-28-30', 'gps-gnss-antennas', 'GPS/GLONASS/IRNSS Combo Antenna, SMA, RG316, 3m', '1575/1602/1176–1227 MHz', 'Multi-constellation GNSS combo antenna with RG316 low-loss cable.', '{"Frequency":"GPS/GLONASS/IRNSS","LNA Gain":"28 dB","Connector":"SMA Male","Cable":"RG316, 3m","Supply Voltage":"3.3–5V","IP Rating":"IP65"}'),
('AT-ANT-IRNSSL1L5', 'at-ant-irnssl1l5', 'gps-gnss-antennas', 'IRNSS/NavIC Dual-Band Antenna, L1+L5', '1176–1227 MHz', 'Dedicated dual-band IRNSS/NavIC antenna covering L1 and L5. For Indian defense and transport.', '{"Frequency":"1176.45 MHz (L5) & 1227.6 MHz (L1)","Type":"Active patch","LNA Gain":"28 dB","Connector":"SMA Male","IP Rating":"IP67","Temperature":"-40°C to +85°C"}'),
('AT-GPS-FDAMP-SMAF-28', 'at-gps-fdamp-smaf-28', 'gps-gnss-antennas', 'GPS In-Line Feeder Amplifier, SMA Female, 28dB', '1575.42 MHz', 'In-line GPS signal amplifier to compensate cable loss on long antenna feeder runs.', '{"Frequency":"1575.42 MHz","Gain":"28 dB","Noise Figure":"< 2.0 dB","Connector":"SMA Female (in/out)","Supply Voltage":"3.3–5V (DC via coax)","Current":"< 25 mA","Impedance":"50 Ω"}'),
('AT-ANT-GPS-HGSCD-NF-40.0-SCADA', 'at-ant-gps-hgscd-nf-400-scada', 'gps-gnss-antennas', 'GPS High-Gain SCADA Antenna, N Female, 40dB LNA', '1575.42 MHz', 'High-gain GPS antenna for SCADA and RTK applications. 40 dB LNA, N Female, ruggedised outdoor.', '{"Frequency":"1575.42 MHz","LNA Gain":"40 dB","Noise Figure":"< 1.0 dB","Connector":"N Female","IP Rating":"IP67","Supply Voltage":"5–12V","Temperature":"-55°C to +85°C","Mount":"Pole mount"}'),

-- ── WiFi ANTENNAS ───────────────────────────────────────────────────────────
('AT-ANT-WIFI-DB-RPSMA205-305-5.0-W', 'at-ant-wifi-db-rpsma205-305-50-w', 'wifi-antennas', 'Dual-band WiFi Antenna, RP-SMA, 5 dBi, Weatherproof', '2400/5150–5850 MHz', 'Dual-band 2.4/5 GHz WiFi antenna with RP-SMA male connector. Weatherproof version.', '{"Frequency":"2.4 GHz & 5 GHz","Gain":"5 dBi","Connector":"RP-SMA Male","Cable":"RG174, 205/305mm","VSWR":"< 2.0:1","Impedance":"50 Ω"}'),
('AT-ANT-WIFI-DB-RPSMA375-7.0', 'at-ant-wifi-db-rpsma375-70', 'wifi-antennas', 'Dual-band WiFi Antenna, RP-SMA, 7 dBi, 375mm', '2400/5150–5850 MHz', 'High-gain dual-band WiFi antenna. Suitable for IEEE 802.11 a/b/g/n/ac access points and CPE.', '{"Frequency":"2.4 & 5 GHz","Gain":"7 dBi","Connector":"RP-SMA Male","Cable":"375mm","VSWR":"< 2.0:1","Impedance":"50 Ω"}'),
('AT-ANT-WIFI-DB-RPSMA430-9.0', 'at-ant-wifi-db-rpsma430-90', 'wifi-antennas', 'Dual-band WiFi Antenna, RP-SMA, 9 dBi, 430mm', '2400/5150–5850 MHz', 'High-gain 9 dBi dual-band WiFi antenna. Ideal for long-range outdoor WiFi links.', '{"Frequency":"2.4 & 5 GHz","Gain":"9 dBi","Connector":"RP-SMA Male","Cable":"430mm","VSWR":"< 2.0:1","Impedance":"50 Ω"}'),
('AT-ANT-WIFI-DB-UFL1.13-120-5.0', 'at-ant-wifi-db-ufl-120-50', 'wifi-antennas', 'Dual-band WiFi Internal Antenna, UFL, 5 dBi, 120mm', '2400/5150–5850 MHz', 'Internal dual-band WiFi antenna with UFL connector and 120mm coax. For embedded routers.', '{"Frequency":"2.4 & 5 GHz","Gain":"5 dBi","Connector":"UFL","Cable":"1.13mm, 120mm","Impedance":"50 Ω","Mount":"Adhesive / clip"}'),
('AT-ANT-WIFI-FGNW-NFST-12.0', 'at-ant-wifi-fgnw-nfst-120', 'wifi-antennas', 'WiFi Fiberglass Networking Antenna, N Female, 12 dBi', '2400–2500 MHz', 'High-gain outdoor fiberglass WiFi omni antenna. N Female, 12 dBi, stainless pole mount.', '{"Frequency":"2400–2500 MHz","Gain":"12 dBi","Connector":"N Female (stainless)","Radome":"Fibreglass UV-stabilised","VSWR":"< 1.5:1","IP Rating":"IP67","Wind Rating":"150 km/h"}'),
('AT-ANT-WIFI-FGNW-NFST-5.0', 'at-ant-wifi-fgnw-nfst-50', 'wifi-antennas', 'WiFi Fiberglass Networking Antenna, N Female, 5 dBi', '2400–2500 MHz', 'Outdoor fiberglass omnidirectional WiFi antenna with 5 dBi gain.', '{"Frequency":"2400–2500 MHz","Gain":"5 dBi","Connector":"N Female","IP Rating":"IP65","VSWR":"< 1.5:1","Mount":"Pole mount"}'),
('AT-ANT-WIFI-YAGI-SMAST58-3-12.0', 'at-ant-wifi-yagi-12dbi', 'wifi-antennas', 'WiFi Yagi Directional Antenna, SMA, 12 dBi', '2400–2500 MHz', 'Directional Yagi for long-range point-to-point WiFi at 2.4 GHz. 12 dBi gain.', '{"Frequency":"2400–2500 MHz","Gain":"12 dBi","Type":"Yagi","Connector":"SMA Male","Cable":"RG58, 3m","HPBW":"≈ 30°","VSWR":"< 1.5:1"}'),
('AT-ANT-WIFI-PP-NF-18.0', 'at-ant-wifi-pp-nf-180', 'wifi-antennas', 'WiFi Panel Antenna, N Female, 18 dBi', '2400–2500 MHz', 'High-gain flat panel directional WiFi antenna for sector coverage and backhaul.', '{"Frequency":"2400–2500 MHz","Gain":"18 dBi","Type":"Panel / flat patch array","Connector":"N Female","HPBW (Az/El)":"≈ 15° / 15°","VSWR":"< 1.5:1","IP Rating":"IP65"}'),
('AT-ANT-WIFI-CEILING-SMA58-500-6.0', 'at-ant-wifi-ceiling-6dbi', 'wifi-antennas', 'WiFi Ceiling Dome Antenna, SMA, 6 dBi, 500mm', '2400–2500 MHz', 'Indoor ceiling-mount omnidirectional WiFi antenna. 6 dBi, SMA male, 500mm cable.', '{"Frequency":"2400–2500 MHz","Gain":"6 dBi","Type":"Ceiling dome","Connector":"SMA Male","Cable":"RG58, 500mm","VSWR":"< 1.5:1","Mount":"Ceiling T-bar / screw"}'),
('AT-ANT-WIFI-HORN-NFST-24.0', 'at-ant-wifi-horn-24dbi', 'wifi-antennas', 'WiFi Horn Antenna, N Female, 24 dBi', '2400–2500 MHz', 'High-gain horn antenna for long-range directional WiFi links. 24 dBi.', '{"Frequency":"2400–2500 MHz","Gain":"24 dBi","Type":"Horn","Connector":"N Female","HPBW":"≈ 10°","VSWR":"< 1.5:1","Material":"Aluminium"}'),

-- ── VHF / UHF ANTENNAS ──────────────────────────────────────────────────────
('AT-ANT-VHF-SMA-DR-3.0', 'at-ant-vhf-sma-dr-30', 'vhf-uhf-antennas', 'VHF Dipole Rubber Duck Antenna, SMA, 3 dBi', '136–174 MHz', 'VHF rubber duck antenna for land mobile radio and military handsets.', '{"Frequency":"136–174 MHz","Gain":"3 dBi","Type":"Rubber duck / dipole","Connector":"SMA Male","Length":"≈ 420mm","Impedance":"50 Ω","VSWR":"< 2.0:1"}'),
('AT-ANT-VHF-RPSMA-DR-3.0', 'at-ant-vhf-rpsma-dr-30', 'vhf-uhf-antennas', 'VHF Dipole Rubber Duck Antenna, RP-SMA, 3 dBi', '136–174 MHz', 'VHF rubber duck antenna with RP-SMA male connector.', '{"Frequency":"136–174 MHz","Gain":"3 dBi","Connector":"RP-SMA Male","Length":"≈ 420mm","Impedance":"50 Ω","VSWR":"< 2.0:1"}'),
('AT-ANT-VHF-SMAR-HHT-3.0', 'at-ant-vhf-smar-hht-30', 'vhf-uhf-antennas', 'VHF Handheld Terminal Antenna, SMA RA, 3 dBi', '136–174 MHz', 'VHF handheld terminal antenna for tactical radio handsets and body-worn devices.', '{"Frequency":"136–174 MHz","Gain":"3 dBi","Connector":"SMA Male RA","Type":"Helical stub","Impedance":"50 Ω","VSWR":"< 2.0:1"}'),
('AT-ANT-VHF-BNC-5.0', 'at-ant-vhf-bnc-50', 'vhf-uhf-antennas', 'VHF Antenna, BNC, 5 dBi', '136–174 MHz', 'VHF antenna with BNC male connector for test equipment and radio scanners.', '{"Frequency":"136–174 MHz","Gain":"5 dBi","Connector":"BNC Male","Impedance":"50 Ω","VSWR":"< 1.5:1"}'),
('AT-ANT-UHF-SMA210-3.5(SL)', 'at-ant-uhf-sma210-35-sl', 'vhf-uhf-antennas', 'UHF Sleeve Antenna, SMA, 3.5 dBi, 210mm', '400–470 MHz', 'UHF sleeve antenna for the 400–470 MHz TETRA/P25 and IoT bands.', '{"Frequency":"400–470 MHz","Gain":"3.5 dBi","Type":"Sleeve","Connector":"SMA Male","Cable":"RG174, 210mm","Impedance":"50 Ω","VSWR":"< 2.0:1"}'),

-- ── HIGH GAIN ANTENNAS ──────────────────────────────────────────────────────
('AT-ANT-GPS-HGM-SMA58-1-35.0', 'at-ant-gps-hgm-sma58-1-350', 'high-gain-antennas', 'GPS High-Gain Active Antenna, SMA, 35dB LNA, 1m Cable', '1575.42 MHz', 'High-gain GPS active antenna with 35 dB LNA for long cable runs.', '{"Frequency":"1575.42 MHz","LNA Gain":"35 dB","Noise Figure":"< 1.0 dB","Connector":"SMA Male","Cable":"RG58, 1m","Supply":"3.3–5V","IP Rating":"IP67","Temperature":"-40°C to +85°C"}'),
('AT-ANT-QGSM-FGNW-NF213-500-10.0', 'at-ant-qgsm-fgnw-nf213-500-100', 'high-gain-antennas', 'GSM High-Gain Fiberglass Antenna, N Female, 10 dBi', '824–2170 MHz', 'High-gain outdoor omnidirectional GSM antenna. 10 dBi, N Female, 500mm radome.', '{"Frequency":"824–2170 MHz","Gain":"10 dBi","Connector":"N Female","Radome":"Fibreglass, 500mm","IP Rating":"IP67","VSWR":"< 1.5:1"}'),
('AT-ANT-WIFI-BFIRE-NF240-500-24.0', 'at-ant-wifi-bfire-nf240-500-240', 'high-gain-antennas', 'WiFi Backfire Antenna, N Female, 24 dBi', '2400–2500 MHz', 'Ultra high-gain backfire directional antenna for long-range 2.4 GHz WiFi links.', '{"Frequency":"2400–2500 MHz","Gain":"24 dBi","Type":"Backfire","Connector":"N Female","HPBW":"≈ 8°","VSWR":"< 1.5:1"}'),
('AT-ANT-WIFI-PRB-NFST-500-24.0', 'at-ant-wifi-prb-nfst-500-240', 'high-gain-antennas', 'WiFi Parabolic Dish Antenna, N Female, 24 dBi', '2400–2500 MHz', 'Parabolic reflector WiFi antenna for long-range point-to-point wireless backhaul.', '{"Frequency":"2400–2500 MHz","Gain":"24 dBi","Type":"Parabolic reflector","Connector":"N Female","HPBW":"≈ 8°","F/B Ratio":"> 35 dB","IP Rating":"IP65"}'),
('AT-ANT-VHF-PM-BNC174-200-6.0', 'at-ant-vhf-pm-bnc174-200-60', 'high-gain-antennas', 'VHF Pole-Mount High-Gain Antenna, BNC, 6 dBi', '136–174 MHz', 'High-gain VHF pole-mount antenna for fixed base station and repeater applications.', '{"Frequency":"136–174 MHz","Gain":"6 dBi","Connector":"BNC Male","Cable":"RG174, 200mm","VSWR":"< 1.5:1","Mount":"Pole","IP Rating":"IP65"}'),

-- ── RFID ANTENNAS ───────────────────────────────────────────────────────────
('AT-ANT-UHF-RFID', 'at-ant-uhf-rfid', 'rfid-antennas', 'UHF RFID Antenna, 865–868 MHz, RHCP', '865–868 MHz', 'UHF RFID antenna for Indian RFID frequency band. Circular polarisation for reliable tag read.', '{"Frequency":"865–868 MHz","Polarization":"RHCP","Gain":"6 dBic","Connector":"SMA Female","VSWR":"< 1.5:1","Impedance":"50 Ω","IP Rating":"IP54"}'),
('AT-ANT-LF-HF-RFID', 'at-ant-lf-hf-rfid', 'rfid-antennas', 'LF/HF RFID Antenna, 125 kHz / 13.56 MHz', '125 kHz / 13.56 MHz', 'Dual-frequency LF and HF RFID antenna for access control and industrial tracking.', '{"Frequency":"125 kHz / 13.56 MHz","Protocol":"EM4100, ISO 15693, NFC","Connector":"SMA Female","Read Range":"Up to 10cm (HF), 8cm (LF)","Impedance":"50 Ω"}'),

-- ── LPA / WIDEBAND ANTENNAS ─────────────────────────────────────────────────
('LPA 20-3000 MHz', 'lpa-20-3000mhz', 'lpa-antennas', 'Log-Periodic Antenna, 20–3000 MHz', '20–3000 MHz', 'Broadband log-periodic dipole array for EMC testing, SIGINT, and spectrum monitoring.', '{"Frequency":"20–3000 MHz","Gain":"6–9 dBi (avg)","Type":"Log-Periodic Dipole Array","Connector":"N Female","Impedance":"50 Ω","Power":"100W"}'),
('LPA 1-30 MHz', 'lpa-1-30mhz', 'lpa-antennas', 'Log-Periodic HF Antenna, 1–30 MHz', '1–30 MHz', 'HF log-periodic antenna for 1–30 MHz monitoring, SIGINT, and shortwave measurement.', '{"Frequency":"1–30 MHz","Gain":"5–8 dBi","Type":"Log-Periodic","Connector":"N Female","Impedance":"50 Ω","Power":"200W"}'),
('LPA 30-500 MHz', 'lpa-30-500mhz', 'lpa-antennas', 'Log-Periodic VHF/UHF Antenna, 30–500 MHz', '30–500 MHz', 'VHF/UHF log-periodic for EMC pre-compliance and military comms monitoring.', '{"Frequency":"30–500 MHz","Gain":"6–9 dBi","Connector":"N Female","Impedance":"50 Ω","Power":"150W"}'),
('LPA 500-6000 MHz', 'lpa-500-6000mhz', 'lpa-antennas', 'Log-Periodic Wideband Antenna, 500 MHz–6 GHz', '500–6000 MHz', 'Wideband log-periodic for 5G/WiFi/cellular spectrum monitoring and EMC testing.', '{"Frequency":"500–6000 MHz","Gain":"7–10 dBi","Connector":"N Female","Impedance":"50 Ω","Power":"50W"}'),

-- ── DUPLEXERS ───────────────────────────────────────────────────────────────
('DUPLEXER-136-174 MHz', 'duplexer-136-174mhz', 'duplexers', 'VHF Cavity Duplexer, 136–174 MHz', '136–174 MHz', 'VHF cavity duplexer for land mobile radio base stations in 136–174 MHz band.', '{"TX Band":"136–148 MHz","RX Band":"148–174 MHz","Insertion Loss TX":"< 1.5 dB","Insertion Loss RX":"< 1.5 dB","TX-RX Isolation":"> 70 dB","VSWR":"< 1.3:1","Power":"50W avg","Connector":"N Female"}'),
('DUPLEXER-703-733MHz', 'duplexer-703-733mhz', 'duplexers', 'LTE Band 28 Cavity Duplexer, 703–733 MHz', '703–788 MHz', 'Cavity duplexer for LTE Band 28 (APT 700) base stations.', '{"TX Band":"703–733 MHz","RX Band":"758–788 MHz","Insertion Loss TX":"< 1.2 dB","TX-RX Isolation":"> 75 dB","VSWR":"< 1.3:1","Power":"100W avg","Connector":"N Female"}'),
('DUPLEXER-758-803MHz', 'duplexer-758-803mhz', 'duplexers', 'LTE Band 20 Cavity Duplexer, 758–803 MHz', '791–862 MHz', 'LTE Band 20 (800 MHz) cavity duplexer for European and Indian 4G base stations.', '{"TX Band":"791–821 MHz","RX Band":"832–862 MHz","Insertion Loss":"< 1.0 dB","TX-RX Isolation":"> 80 dB","PIM":"< –153 dBc @ 2×43dBm","Connector":"N Female","Power":"100W avg"}'),
('DUPLEXER-1710-1785MHz', 'duplexer-1710-1785mhz', 'duplexers', 'LTE Band 3 Cavity Duplexer, 1710–1785 MHz', '1710–1880 MHz', 'LTE Band 3 (1800 MHz) cavity duplexer for Indian 4G base station deployments.', '{"TX Band":"1710–1785 MHz","RX Band":"1805–1880 MHz","Insertion Loss":"< 0.9 dB","TX-RX Isolation":"> 80 dB","PIM":"< –153 dBc @ 2×43dBm","VSWR":"< 1.3:1","Power":"100W avg","Connector":"N Female"}'),

-- ── DIPLEXERS ───────────────────────────────────────────────────────────────
('OV-DIPLEXR-006072023', 'ov-diplexr-006072023', 'diplexers', 'RF Diplexer, Dual-Band Frequency Combiner', 'Custom bands', 'RF diplexer for combining or separating two distinct frequency bands on a single antenna port.', '{"Type":"Diplexer","Topology":"Cavity / LC","Insertion Loss":"< 1.5 dB per port","Port Isolation":"> 40 dB","VSWR":"< 1.3:1","Connector":"SMA / N-Type Female","Impedance":"50 Ω","Custom bands":"Available on request"}'),

-- ── POWER SPLITTERS ─────────────────────────────────────────────────────────
('AT-LPW-SP-2-500-6000', 'at-lpw-sp-2-500-6000', 'power-splitters', '1×2 Low Power RF Splitter, 500–6000 MHz', '500–6000 MHz', 'Compact 1-to-2 resistive power splitter covering 500 MHz to 6 GHz.', '{"Frequency":"500–6000 MHz","Division":"1×2","Insertion Loss":"< 4.0 dB (each port)","Amplitude Balance":"±0.5 dB","Phase Balance":"±5°","Port Isolation":"> 20 dB","VSWR":"< 1.5:1","Connector":"SMA Female","Power":"1W max"}'),
('AT-LPW-SP-2-1500-8000', 'at-lpw-sp-2-1500-8000', 'power-splitters', '1×2 Low Power RF Splitter, 1500–8000 MHz', '1500–8000 MHz', '1-to-2 power splitter for cellular and microwave bands from 1.5–8 GHz.', '{"Frequency":"1500–8000 MHz","Division":"1×2","Insertion Loss":"< 4.5 dB","Amplitude Balance":"±0.5 dB","Port Isolation":"> 20 dB","VSWR":"< 1.5:1","Connector":"SMA Female"}'),
('AT-LPW-SP-4-8000', 'at-lpw-sp-4-8000', 'power-splitters', '1×4 Low Power RF Splitter, up to 8000 MHz', '500–8000 MHz', '1-to-4 power splitter covering up to 8 GHz for MIMO test beds and multi-receiver systems.', '{"Frequency":"500–8000 MHz","Division":"1×4","Insertion Loss":"< 7.5 dB (each port)","Amplitude Balance":"±0.5 dB","Phase Balance":"±5°","Port Isolation":"> 20 dB","VSWR":"< 1.5:1","Connector":"SMA Female"}'),
('AT-LPW-SP-16-6000', 'at-lpw-sp-16-6000', 'power-splitters', '1×16 Low Power RF Splitter, up to 6000 MHz', '500–6000 MHz', '1-to-16 power splitter for large DAS and multi-antenna test systems.', '{"Frequency":"500–6000 MHz","Division":"1×16","Insertion Loss":"< 14 dB (each port)","Amplitude Balance":"±1.0 dB","VSWR":"< 1.8:1","Connector":"SMA Female","Housing":"Aluminium"}'),
('AT-gps-splitter', 'at-gps-splitter', 'power-splitters', 'GPS Active Splitter, 1×4, 1575 MHz', '1575.42 MHz', 'Active GPS signal splitter distributing one GPS antenna to 4 receivers without degradation.', '{"Frequency":"1575.42 MHz","Division":"1×4 active","Gain":"0 dB net (compensated)","DC Pass":"Port 1 (antenna power)","Supply":"5V, 200mA","Connector":"SMA Female","Noise Figure":"< 3 dB"}'),

-- ── ATTENUATORS ─────────────────────────────────────────────────────────────
('AT-ATT-FIXED-SMA', 'at-att-fixed-sma', 'attenuators', 'Fixed RF Attenuator, SMA, 1–30 dB', 'DC–6 GHz', 'Fixed precision RF attenuator in SMA inline package. Values: 1, 2, 3, 6, 10, 20, 30 dB.', '{"Frequency":"DC–6 GHz","Attenuation":"1 / 2 / 3 / 6 / 10 / 20 / 30 dB","Power":"2W","VSWR":"< 1.3:1","Connector":"SMA Male–Female","Accuracy":"±0.5 dB","Impedance":"50 Ω"}'),
('AttenuatorVA-Series', 'attenuator-va-series', 'attenuators', 'Variable RF Attenuator, SMA, 0–90 dB', 'DC–4 GHz', 'Manual continuously variable RF attenuator. Available 0–30, 0–60, 0–90 dB variants.', '{"Frequency":"DC–4 GHz","Attenuation Range":"0–30, 0–60, 0–90 dB","Step Resolution":"Continuous / 10 dB step","VSWR":"< 1.5:1 @ 1 GHz","Power":"1W","Connector":"SMA Female","Control":"Manual rotary dial"}'),
('AttenuatordkVA-90', 'attenuator-dkva-90', 'attenuators', 'Digital-Step Variable Attenuator, 0–90 dB', 'DC–3 GHz', 'Digital-step variable attenuator with 0–90 dB range in 10 dB steps.', '{"Frequency":"DC–3 GHz","Range":"0–90 dB","Step Size":"10 dB","VSWR":"< 1.8:1","Power":"0.5W","Connector":"SMA Female","Control":"Push-button digital"}'),

-- ── COUPLERS ────────────────────────────────────────────────────────────────
('AT-COUPLER-800-2500', 'at-coupler-800-2500', 'couplers', 'Directional Coupler, 800–2500 MHz, SMA', '800–2500 MHz', 'Directional RF coupler for power monitoring across the cellular spectrum 800–2500 MHz.', '{"Frequency":"800–2500 MHz","Coupling":"10 / 20 / 30 dB options","Directivity":"> 20 dB","Insertion Loss":"< 0.5 dB","VSWR":"< 1.3:1","Power":"20W","Connector":"SMA Female","Impedance":"50 Ω"}'),
('AT-COUPLER-117', 'at-coupler-117', 'couplers', 'Hybrid 90° Coupler, SMA', '800–2500 MHz', '90° hybrid coupler for IQ demodulators, antenna feed networks, and balanced amplifiers.', '{"Frequency":"800–2500 MHz","Type":"90° Hybrid","Coupling":"3 dB (equal split)","Phase Balance":"90° ±5°","Amplitude Balance":"±0.5 dB","Isolation":"> 20 dB","Connector":"SMA Female","Power":"5W"}'),
('ZGDC35-93HP+', 'zgdc35-93hp-plus', 'couplers', 'High-Power Directional Coupler, 35 dB, N Female', '700–2700 MHz', 'High-power 35 dB directional coupler for base station power monitoring.', '{"Frequency":"700–2700 MHz","Coupling":"35 dB","Directivity":"> 25 dB","Insertion Loss":"< 0.3 dB","Power":"200W avg","VSWR":"< 1.2:1","Connector":"N Female"}'),

-- ── BAND PASS FILTERS ───────────────────────────────────────────────────────
('AT-BPF-GSM900', 'at-bpf-gsm900', 'band-pass-filters', 'GSM 900 Bandpass Filter, 880–960 MHz', '880–960 MHz', 'Cavity bandpass filter for GSM 900 MHz band. High rejection for base station use.', '{"Passband":"880–960 MHz","Insertion Loss":"< 1.5 dB","Return Loss":"> 18 dB","Rejection (±50 MHz)":"> 50 dBc","Power":"20W avg","Connector":"N Female","Temperature":"-40°C to +85°C"}'),
('AT-BPF-LTE1800', 'at-bpf-lte1800', 'band-pass-filters', 'LTE Band 3 Bandpass Filter, 1710–1880 MHz', '1710–1880 MHz', 'Cavity bandpass filter for LTE Band 3 (1800 MHz) — critical for Indian 4G deployments.', '{"Passband":"1710–1880 MHz","Insertion Loss":"< 1.2 dB","Return Loss":"> 20 dB","Rejection (±100 MHz)":"> 55 dBc","Power":"20W avg","Connector":"N Female"}'),
('AT-BPF-2400-WIFI', 'at-bpf-2400-wifi', 'band-pass-filters', 'WiFi 2.4 GHz ISM Bandpass Filter', '2400–2485 MHz', 'Compact bandpass filter for 2.4 GHz WiFi/ISM band. Suppresses out-of-band interference.', '{"Passband":"2400–2485 MHz","Insertion Loss":"< 1.0 dB","Return Loss":"> 18 dB","Rejection (±200 MHz)":"> 40 dBc","Power":"5W","Connector":"SMA Female"}'),

-- ── LIGHTNING ARRESTORS ─────────────────────────────────────────────────────
('AT-LA-N-2000', 'at-la-n-2000', 'lightning-arrestors', 'RF Lightning Arrestor, N Type, DC–2 GHz', 'DC–2000 MHz', 'Gas discharge tube RF lightning arrestor with N connectors. Protects antenna feedlines to 2 GHz.', '{"Frequency":"DC–2000 MHz","Insertion Loss":"< 0.3 dB","VSWR":"< 1.2:1","Discharge Current":"20 kA (8/20 µs)","DC Breakdown":"90V","Connector":"N Male – N Female","IP Rating":"IP67","Temperature":"-40°C to +85°C"}'),
('AT-LA-N6000', 'at-la-n6000', 'lightning-arrestors', 'RF Lightning Arrestor, N Type, DC–6 GHz', 'DC–6000 MHz', 'Wideband lightning arrestor covering DC to 6 GHz. Suitable for 5G sub-6 GHz feedlines.', '{"Frequency":"DC–6000 MHz","Insertion Loss":"< 0.5 dB","VSWR":"< 1.3:1","Discharge Current":"20 kA (8/20 µs)","DC Breakdown":"90V","Connector":"N Male – N Female","IP Rating":"IP67"}'),

-- ── RF CABLE ASSEMBLIES ─────────────────────────────────────────────────────
('AT-CA-SMAM-SMAM-XXX', 'at-ca-smam-smam-custom', 'rf-cable-assemblies', 'SMA Male to SMA Male Cable Assembly, Custom Length', 'DC–6 GHz', 'SMA to SMA coaxial cable assembly on RG174/RG316. Custom lengths 50mm–5000mm.', '{"Frequency":"DC–6 GHz","Connectors":"SMA Male both ends","Cable Options":"RG174, RG316, RG58","Impedance":"50 Ω","VSWR":"< 1.3:1 @ 3 GHz","Length":"Custom (50mm–5000mm)","Insertion Loss":"< 1.5 dB/m @ 1 GHz"}'),
('AT-CA-RPSMA-UFL-100-MH2', 'at-ca-rpsma-ufl-100-mh2', 'rf-cable-assemblies', 'RP-SMA to UFL/MHF2 Pigtail, 100mm', 'DC–6 GHz', 'RP-SMA Male to UFL/MHF2 pigtail, 100mm. For mini-PCIe WiFi/LTE cards to external antennas.', '{"Frequency":"DC–6 GHz","Connector A":"RP-SMA Male","Connector B":"UFL / MHF2","Cable":"1.13mm coax, 100mm","Impedance":"50 Ω","Insertion Loss":"< 0.5 dB @ 2.4 GHz"}'),
('AT-CA-RPSMA-UFL-140-XX', 'at-ca-rpsma-ufl-140', 'rf-cable-assemblies', 'RP-SMA to UFL Pigtail, 140mm', 'DC–6 GHz', 'RP-SMA Male to UFL pigtail, 140mm 1.13mm coax. For boards with more routing space.', '{"Connector A":"RP-SMA Male","Connector B":"UFL (IPEX)","Cable":"1.13mm, 140mm","Impedance":"50 Ω","Frequency":"DC–6 GHz"}'),
('AT-CA-BNCM-SMAM-1000', 'at-ca-bncm-smam-1000', 'rf-cable-assemblies', 'BNC Male to SMA Male Cable Assembly, 1000mm', 'DC–3 GHz', 'BNC to SMA cable assembly on RG174, 1000mm. For test bench connections.', '{"Connector A":"BNC Male","Connector B":"SMA Male","Cable":"RG174, 1000mm","Frequency":"DC–3 GHz","Impedance":"50 Ω","VSWR":"< 1.3:1"}'),
('AT-CA-SMABH-UFL-100-XX', 'at-ca-smabh-ufl-100', 'rf-cable-assemblies', 'SMA Bulkhead to UFL Pigtail, 100mm', 'DC–6 GHz', 'SMA Female Bulkhead to UFL for panel-mount antenna to internal PCB connections.', '{"Connector A":"SMA Female Bulkhead","Connector B":"UFL","Cable":"1.13mm, 100mm","Impedance":"50 Ω","Frequency":"DC–6 GHz","Mount":"Panel / bulkhead"}'),
('AT-CA-UFL-UFL-40-1.13', 'at-ca-ufl-ufl-40-113', 'rf-cable-assemblies', 'UFL to UFL Jumper, 40mm, 1.13mm Coax', 'DC–6 GHz', 'Ultra-short UFL to UFL board-to-board RF jumper. 40mm 1.13mm coax.', '{"Connector A":"UFL (IPEX)","Connector B":"UFL (IPEX)","Cable":"1.13mm, 40mm","Impedance":"50 Ω","Frequency":"DC–6 GHz","Insertion Loss":"< 0.2 dB @ 2.4 GHz"}'),
('AT-CA-NM-SMAF-BH-XXX', 'at-ca-nm-smaf-bh-custom', 'rf-cable-assemblies', 'N Male to SMA Female Bulkhead Assembly, Custom Length', 'DC–6 GHz', 'N Male to SMA Female Bulkhead for outdoor N-type to indoor SMA connections. Custom lengths.', '{"Connector A":"N Male","Connector B":"SMA Female Bulkhead","Cable Options":"RG174, RG316, LMR-195","Length":"Custom","Frequency":"DC–6 GHz","Impedance":"50 Ω"}'),
('AT-CA-MMCXRT-SMA-ST-RG316', 'at-ca-mmcxrt-sma-rg316', 'rf-cable-assemblies', 'MMCX Right-Angle to SMA Straight Cable, RG316', 'DC–6 GHz', 'MMCX right-angle to SMA on RG316. For compact WiFi/cellular module connections.', '{"Connector A":"MMCX Male Right-Angle","Connector B":"SMA Male Straight","Cable":"RG316","Frequency":"DC–6 GHz","Impedance":"50 Ω","VSWR":"< 1.3:1"}'),

-- ── POWER AMPLIFIERS ────────────────────────────────────────────────────────
('AT-PA-1.0W', 'at-pa-10w', 'power-amplifiers', 'RF Power Amplifier Module, 1W', '800–2500 MHz', '1W (30 dBm) RF power amplifier module for cellular band signal boosters.', '{"Frequency":"800–2500 MHz","Output Power":"30 dBm (1W)","Gain":"30 dB","IP3":"+40 dBm","Supply":"+5V / 800mA","Connector":"SMA Female","Efficiency":"25%"}'),
('AT-PA-2.0W', 'at-pa-20w', 'power-amplifiers', 'RF Power Amplifier Module, 2W', '800–2500 MHz', '2W (33 dBm) RF power amplifier for repeaters and signal boosters.', '{"Frequency":"800–2500 MHz","Output Power":"33 dBm (2W)","Gain":"33 dB","Supply":"+5V / 1.5A","Connector":"SMA Female","Efficiency":"28%","Cooling":"Heat sink required"}'),
('AT-PA-LNA', 'at-pa-lna', 'power-amplifiers', 'Low Noise Amplifier Module, 0.5–3 GHz', '500–3000 MHz', 'Ultra-low noise amplifier module. 20 dB gain, < 1 dB noise figure, 500 MHz to 3 GHz.', '{"Frequency":"500–3000 MHz","Gain":"20 dB","Noise Figure":"< 1 dB","IP3 (Input)":"+10 dBm","Supply":"+3.3 or +5V / 80mA","Connector":"SMA Female","P1dB":"+18 dBm"}'),

-- ── WAVEGUIDE COMPONENTS ────────────────────────────────────────────────────
('AT-ANT-WAVEGUIDE-coupler', 'at-ant-waveguide-coupler', 'waveguide', 'X-Band Waveguide Directional Coupler', '8.2–12.4 GHz', 'X-band waveguide directional coupler for power monitoring in radar and SATCOM. WR-90 flange.', '{"Frequency":"8.2–12.4 GHz","Coupling":"20 / 30 dB","Directivity":"> 25 dB","Insertion Loss":"< 0.2 dB","Flange":"WR-90","Material":"Brass, silver-plated","VSWR":"< 1.15:1"}'),
('AT-ANT-WAVEGUIDE-load', 'at-ant-waveguide-load', 'waveguide', 'X-Band Waveguide Matched Termination Load', '8.2–12.4 GHz', 'Waveguide matched load for X-band systems. For terminating unused ports and calibration.', '{"Frequency":"8.2–12.4 GHz","Return Loss":"> 30 dB","Power":"5W avg (10W peak)","Flange":"WR-90","Material":"Brass, silver-plated","Temperature":"-40°C to +100°C"}')

ON CONFLICT (slug) DO UPDATE
  SET name = EXCLUDED.name,
      short_spec = EXCLUDED.short_spec,
      frequency_range = EXCLUDED.frequency_range,
      description = EXCLUDED.description,
      specs = EXCLUDED.specs,
      updated_at = NOW();
